//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int Id { get; set; }
        public string dni { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string sexo { get; set; }
        public string Contrasena { get; set; }
        public string correo { get; set; }
    }
}
